; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32dev
framework = espidf
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
# Force the console to use the hardware UART
build_flags = 
    -D CONFIG_ESP_CONSOLE_UART_DEFAULT=1
    -D CONFIG_ESP_CONSOLE_UART_BAUDRATE=115200

[env:esp32cam]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32cam
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
monitor_rts = 0 ; Stop monitor from toggling reset
monitor_dtr = 0 ; Stop monitor from toggling GPIO0
monitor_filters = esp32_exception_decoder
lib_deps = esp32-camera
board_build.partitions = huge_app.csv
build_src_filter = +<../cam_firmware/>